name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - name: Checking your code format
        run: sbt +scalafmtCheck
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run tests
        run: |
          sbt +test

  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2
